### ISSUE TITLE
Coracle korge is not downloading

### ISSUE THREAD

**Issue by Kietyo** [orllewin/coracle#1]
The folder is empty when cloned into Intellij:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/5054996/166864947-80c85d08-9ee6-4b48-b632-12f9b6acd91c.png">

Here's how the folder looks like in the repo btw:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/5054996/166864997-5627f5a4-3c06-4c1e-88df-c92dbf41f48f.png">

**Comment by orllewin** [comment]
Fixed 👍🏼
